### ISSUE TITLE
please add x86 build

### ISSUE THREAD

**Issue by DimastyK** [exoticorn/upkr#10]
I will be very grateful

**Comment by MobyGamer** [comment]
There is already DOS x86 unpacker source in the repo, so what exactly are you asking for?

**Comment by DimastyK** [comment]
I asked win32 program

**Comment by exoticorn** [comment]
I added a 32bit windows build to the release.

**Comment by DimastyK** [comment]
yup, it works. will test tmw. thanks a lot!
